---
title: "hw05-lindsey-chung"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# De Mere's Problem

## Problem 1

```{r}
library(dieroller)

die1 = die()

sample = roll(die1, times = 4000)
count = 0
for (i in 1:1000) {
  if (sample[4 * (i-1) + 1] == 6) {
    count = count + 1
  } else if (sample[4 * (i-1) + 2] == 6) {
    count = count + 1
  } else if (sample[4 * (i-1) + 3] == 6) {
    count = count + 1
  } else if (sample[4 * (i-1) + 4] == 6) {
    count = count + 1
  }
}

# Number of games out of 1000 that have at least one 6:
count

# Relative frequency:
count / 1000

```

## Problem 2

```{r}
sample2 = roll(die1, times = 48000)
count2 = 0
for (i in 1:1000) {
  checker = rep(FALSE, 24)
  for (j in 1:24) {
    if (sample2[48 * (i-1) + 2*j - 1] == 6 & sample2[48 * (i-1) + 2*j] == 6) {
      checker[j] = TRUE
    }
  }
  if (any(checker)) {
    count2 = count2 + 1
  }
}

# Number of games out of 1000 that have at least one double 6:
count2

# Relative frequency:
count2 / 1000

```

for (j in 1:24) {
    if (any(sample2[48 * (i-1) + 2*j - 1] == 6 & sample2[48 * (i-1) + 2*j] == 6))
  }
  if (any(for (j in 1:24) {
    sample2[48 * (i-1) + 2*j - 1] == 6 & sample2[48 * (i-1) + 2*j] == 6
  })) {
      count2 = count2 + 1
  }
